In [237]:
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from pathlib import Path
import csv
import html
import random
import yaml
import pandas as pd
import json

import requests

# CSV, JSON, YAML

**Fred Brosman**

*05.05.2026*

# Ülesanne 1 — Test Trivia API abil
Looge programm, mis võimaldab kasutajal läbida testi, kasutades Trivia API küsimusi, ning salvestada tulemused JSON-faili.

Programm peab:

1. küsima kasutajalt kasutajanime
2. laadima Trivia API-st kategooriad
3. laskma kasutajal valida kategooria
4. küsima küsimuste arvu vahemikus 1–20
5. laskma valida küsimuste tüübi: `multiple` või `boolean`
6. tegema API päringu vastavalt kasutaja valikutele
7. kuvama küsimused ja vastusevariandid
8. kontrollima kasutaja vastuseid
9. kuvama testi lõpus skoori ja õiged vastused
10. salvestama tulemuse CSV-faili
11. kuvama tulemuste statistika: TOP 5 ja keskmine tulemus

Lahenduses kasutan:

- klassi `TriviaQuestion`, mis hoiab ühe küsimuse andmeid
- klassi `TriviaResult`, mis hoiab ühe testi tulemuse andmeid
- klassi `TriviaGame`, mis juhib testi läbimist
- eraldi funktsioone API päringute, CSV salvestamise ja statistika jaoks

## Konstandid

In [238]:
MIN_QUESTION_COUNT = 1
MAX_QUESTION_COUNT = 20

QUESTION_TYPES = {"multiple", "boolean"}

CATEGORIES_URL = "https://opentdb.com/api_category.php"
QUESTIONS_URL = "https://opentdb.com/api.php"

RESULTS_FILE = Path("trivia_tulemused.csv")

DEFAULT_TOP_COUNT = 5
REQUEST_TIMEOUT = 10

CSV_FIELDNAMES = [
    "kasutajanimi",
    "kategooria",
    "küsimuste_arv",
    "tüüp",
    "skoor",
    "kuupäev",
]

## 1.1 Klass TriviaQuestion

See klass kirjeldab ühte Trivia API-st saadud küsimust.

Igal küsimusel on:

- küsimuse tekst
- õige vastus
- valed vastused
- küsimuse tüüp
- kategooria

In [239]:
@dataclass
class TriviaQuestion:
    """
    Klass ühe Trivia küsimuse andmete hoidmiseks.

    Attributes
    ----------
    category : str
        Küsimuse kategooria.
    question_type : str
        Küsimuse tüüp: multiple või boolean.
    question_text : str
        Küsimuse tekst.
    correct_answer : str
        Õige vastus.
    incorrect_answers : list[str]
        Valede vastuste nimekiri.
    """

    category: str
    question_type: str
    question_text: str
    correct_answer: str
    incorrect_answers: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        """
        Kontrollib, et küsimuse põhiandmed oleksid korrektsed.
        """
        if not self.category or not self.category.strip():
            raise ValueError("Kategooria ei tohi olla tühi.")

        if self.question_type not in QUESTION_TYPES:
            raise ValueError("Küsimuse tüüp peab olema 'multiple' või 'boolean'.")

        if not self.question_text or not self.question_text.strip():
            raise ValueError("Küsimuse tekst ei tohi olla tühi.")

        if not self.correct_answer or not self.correct_answer.strip():
            raise ValueError("Õige vastus ei tohi olla tühi.")

        self.category = self.category.strip()
        self.question_text = self.question_text.strip()
        self.correct_answer = self.correct_answer.strip()

    def get_shuffled_answers(self) -> list[str]:
        """
        Tagastab kõik vastusevariandid juhuslikus järjekorras.

        Returns
        -------
        list[str]
            Segatud vastusevariantide nimekiri.
        """
        answers = self.incorrect_answers + [self.correct_answer]
        random.shuffle(answers)
        return answers

    def is_correct(self, answer: str) -> bool:
        """
        Kontrollib, kas kasutaja vastus on õige.

        Parameters
        ----------
        answer : str
            Kasutaja valitud vastus.

        Returns
        -------
        bool
            True, kui vastus on õige. False, kui vastus on vale.
        """
        return answer == self.correct_answer

    def __str__(self) -> str:
        """
        Tagastab küsimuse loetava tekstiesituse.
        """
        return f"{self.category} | {self.question_text}"

## 1.2 Klass TriviaResult

See klass kirjeldab ühe testi tulemust.

Tulemusse salvestan:

- kasutajanime
- kategooria
- küsimuste arvu
- küsimuste tüübi
- skoori
- kuupäeva ja kellaaja

Seda klassi on hiljem mugav kasutada CSV-faili salvestamisel.

In [240]:
@dataclass
class TriviaResult:
    """
    Klass ühe testi tulemuse hoidmiseks.

    Attributes
    ----------
    username : str
        Mängija nimi.
    category : str
        Küsimuste kategooria.
    question_count : int
        Küsimuste arv.
    question_type : str
        Küsimuste tüüp.
    score : int
        Õigete vastuste arv.
    created_at : datetime
        Testi tegemise kuupäev ja kellaaeg.
    """

    username: str
    category: str
    question_count: int
    question_type: str
    score: int
    created_at: datetime = field(default_factory=datetime.now)

    def __post_init__(self) -> None:
        """
        Kontrollib, et tulemuse andmed oleksid korrektsed.
        """
        if not self.username or not self.username.strip():
            raise ValueError("Kasutajanimi ei tohi olla tühi.")

        if not self.category or not self.category.strip():
            raise ValueError("Kategooria ei tohi olla tühi.")

        if self.question_count < MIN_QUESTION_COUNT or self.question_count > MAX_QUESTION_COUNT:
            raise ValueError(
                f"Küsimuste arv peab olema vahemikus "
                f"{MIN_QUESTION_COUNT} kuni {MAX_QUESTION_COUNT}."
            )

        if self.question_type not in QUESTION_TYPES:
            raise ValueError("Küsimuse tüüp peab olema 'multiple' või 'boolean'.")

        if self.score < 0 or self.score > self.question_count:
            raise ValueError("Skoor ei saa olla väiksem kui 0 ega suurem kui küsimuste arv.")

        self.username = self.username.strip()
        self.category = self.category.strip()

    def percentage(self) -> float:
        """
        Arvutab tulemuse protsendina.

        Returns
        -------
        float
            Tulemus protsendina.
        """
        return round(self.score / self.question_count * 100, 2)

    def to_csv_row(self) -> dict[str, str | int]:
        """
        Teisendab tulemuse CSV-faili rea kujule.

        Returns
        -------
        dict
            Sõnastik, kus võtmed vastavad CSV veergudele.
        """
        return {
            "kasutajanimi": self.username,
            "kategooria": self.category,
            "küsimuste_arv": self.question_count,
            "tüüp": self.question_type,
            "skoor": self.score,
            "kuupäev": self.created_at.strftime("%Y-%m-%d %H:%M:%S")
        }

    def __str__(self) -> str:
        """
        Tagastab tulemuse loetava tekstiesituse.
        """
        return (
            f"{self.username} | "
            f"{self.category} | "
            f"{self.score}/{self.question_count} | "
            f"{self.percentage()}%"
        )

## 1.3 Klass TriviaGame

See klass juhib testi läbimist.

Klassis hoian:

- kasutajanime
- küsimuste nimekirja
- kasutaja vastuseid
- skoori

Klassi meetodid kuvavad küsimused, küsivad kasutaja vastust, kontrollivad vastust ja näitavad testi lõpus tulemuse.

In [241]:
@dataclass
class TriviaGame:
    """
    Klass Trivia testi läbiviimiseks.

    Attributes
    ----------
    username : str
        Mängija nimi.
    questions : list[TriviaQuestion]
        Trivia küsimuste nimekiri.
    user_answers : list[tuple[TriviaQuestion, str]]
        Kasutaja vastused koos küsimustega.
    score : int
        Õigete vastuste arv.
    """

    username: str
    questions: list[TriviaQuestion]
    user_answers: list[tuple[TriviaQuestion, str]] = field(default_factory=list)
    score: int = 0

    def __post_init__(self) -> None:
        """
        Kontrollib, et mängu põhiandmed oleksid korrektsed.
        """
        if not self.username or not self.username.strip():
            raise ValueError("Kasutajanimi ei tohi olla tühi.")

        if not self.questions:
            raise ValueError("Küsimuste nimekiri ei tohi olla tühi.")

        self.username = self.username.strip()

    def ask_one_question(self, question: TriviaQuestion, question_number: int) -> None:
        """
        Kuvab ühe küsimuse, küsib vastuse ja kontrollib seda.

        Parameters
        ----------
        question : TriviaQuestion
            Küsimus, mida kasutajale kuvatakse.
        question_number : int
            Küsimuse järjekorranumber.
        """
        answers = question.get_shuffled_answers()

        print()
        print(f"Küsimus {question_number}: {question.question_text}")

        for index, answer in enumerate(answers, start=1):
            print(f"{index}. {answer}")

        user_choice = self.ask_answer_number(len(answers))
        user_answer = answers[user_choice - 1]

        self.user_answers.append((question, user_answer))

        if question.is_correct(user_answer):
            self.score += 1
            print("Õige!")
        else:
            print(f"Vale. Õige vastus oli: {question.correct_answer}")

    def ask_answer_number(self, answer_count: int) -> int:
        """
        Küsib kasutajalt vastuse numbri ja kontrollib sisendit.

        Parameters
        ----------
        answer_count : int
            Mitu vastusevarianti küsimusel on.

        Returns
        -------
        int
            Kasutaja valitud vastuse number.
        """
        while True:
            try:
                choice = int(input("Vali vastuse number: "))

                if 1 <= choice <= answer_count:
                    return choice

                print("Sellist vastusevarianti ei ole.")

            except ValueError:
                print("Palun sisesta vastuse number.")

    def run(self) -> None:
        """
        Käivitab testi ja käib kõik küsimused läbi.
        """
        print(f"Alustame testi. Mängija: {self.username}")

        for index, question in enumerate(self.questions, start=1):
            self.ask_one_question(question, index)

    def print_score(self) -> None:
        """
        Kuvab testi lõppskoori.
        """
        print()
        print(f"Teie skoor: {self.score}/{len(self.questions)}")

    def print_correct_answers(self) -> None:
        """
        Kuvab testi lõpus kõik õiged vastused.
        """
        print()
        print("Õiged vastused:")

        for index, question in enumerate(self.questions, start=1):
            print(f"{index}. {question.question_text}")
            print(f"   Õige vastus: {question.correct_answer}")

    def create_result(self) -> TriviaResult:
        """
        Loob mängu põhjal TriviaResult objekti.

        Returns
        -------
        TriviaResult
            Testi tulemus.
        """
        first_question = self.questions[0]

        return TriviaResult(
            username=self.username,
            category=first_question.category,
            question_count=len(self.questions),
            question_type=first_question.question_type,
            score=self.score
        )

## 1.4 API funktsioonid

Selles osas loon funktsioonid, mis suhtlevad Open Trivia DB API-ga.

Vaja on kahte põhilist asja:

1. laadida kõik kategooriad
2. laadida küsimused kasutaja valikute põhjal

API tagastab andmed JSON-kujul. Pythonis saan neid kasutada sõnastike ja listidena.

In [242]:
def load_categories() -> list[dict]:
    """
    Laeb Open Trivia DB API-st kõik kategooriad.

    Returns
    -------
    list[dict]
        Kategooriate nimekiri. Igal kategoorial on id ja name.
    """
    try:
        response = requests.get(CATEGORIES_URL, timeout=REQUEST_TIMEOUT)
        response.raise_for_status()
        data = response.json()

        return data["trivia_categories"]

    except requests.RequestException as error:
        raise RuntimeError("Kategooriate laadimine ebaõnnestus.") from error

    except ValueError as error:
        raise RuntimeError("API ei tagastanud korrektset JSON-vastust.") from error

    except KeyError as error:
        raise RuntimeError("API vastuses puudub kategooriate nimekiri.") from error


def print_categories(categories: list[dict]) -> None:
    """
    Väljastab kategooriad ekraanile.

    Parameters
    ----------
    categories : list[dict]
        Kategooriate nimekiri.
    """
    print("Saadaolevad kategooriad:")
    print()

    for category in categories:
        print(f'{category["id"]}: {category["name"]}')

## 1.5 Küsimuste laadimine API-st

Järgmine funktsioon teeb päringu küsimuste jaoks.

Kasutaja valib:

- kategooria ID
- küsimuste arvu
- küsimuse tüübi

API vastuses on küsimused koos õigete ja valede vastustega.  
Need teisendan `TriviaQuestion` objektideks.

In [243]:
def create_question_from_api_data(question_data: dict) -> TriviaQuestion:
    """
    Teisendab API-st saadud ühe küsimuse TriviaQuestion objektiks.

    Parameters
    ----------
    question_data : dict
        API-st saadud ühe küsimuse andmed.

    Returns
    -------
    TriviaQuestion
        Küsimuse objekt.
    """
    category = html.unescape(question_data["category"])
    question_type = html.unescape(question_data["type"])
    question_text = html.unescape(question_data["question"])
    correct_answer = html.unescape(question_data["correct_answer"])

    incorrect_answers = [
        html.unescape(answer)
        for answer in question_data["incorrect_answers"]
    ]

    return TriviaQuestion(
        category=category,
        question_type=question_type,
        question_text=question_text,
        correct_answer=correct_answer,
        incorrect_answers=incorrect_answers
    )

def fetch_questions(
    amount: int,
    category_id: int,
    question_type: str
) -> list[TriviaQuestion]:
    """
    Laeb API-st küsimused ja tagastab need TriviaQuestion objektidena.
    """
    params = {
        "amount": amount,
        "category": category_id,
        "type": question_type,
    }

    try:
        response = requests.get(
            QUESTIONS_URL,
            params=params,
            timeout=REQUEST_TIMEOUT,
        )
        response.raise_for_status()
        data = response.json()

    except requests.RequestException as error:
        raise RuntimeError("Küsimuste laadimine ebaõnnestus.") from error

    except ValueError as error:
        raise RuntimeError("API ei tagastanud korrektset JSON-vastust.") from error

    if data.get("response_code") != 0:
        raise ValueError(
            "API ei tagastanud küsimusi. "
            "Proovi teist kategooriat või väiksemat küsimuste arvu."
        )

    question_items = data.get("results", [])
    if not question_items:
        raise ValueError("API vastuses ei olnud ühtegi küsimust.")

    return [
        create_question_from_api_data(question_data)
        for question_data in question_items
    ]

## 1.6 Kasutaja valikute küsimine

Selles osas loon funktsioonid, mis küsivad kasutajalt testi seaded.

Küsitakse:

- kasutajanimi
- kategooria ID
- küsimuste arv
- küsimuste tüüp

Iga funktsioon kontrollib ka sisendit, et programm vale sisendi korral kohe katki ei läheks.

In [244]:
def ask_username() -> str:
    """
    Küsib kasutajalt kasutajanime.

    Returns
    -------
    str
        Kasutaja sisestatud nimi.
    """
    while True:
        username = input("Sisesta kasutajanimi: ").strip()

        if username:
            return username

        print("Kasutajanimi ei tohi olla tühi.")


def ask_category(categories: list[dict]) -> tuple[int, str]:
    """
    Küsib kasutajalt kategooria ID ja kontrollib, kas see on olemas.

    Parameters
    ----------
    categories : list[dict]
        API-st saadud kategooriate nimekiri.

    Returns
    -------
    tuple[int, str]
        Valitud kategooria ID ja kategooria nimi.
    """
    valid_categories = {}

    for category in categories:
        valid_categories[category["id"]] = category["name"]

    while True:
        try:
            category_id = int(input("Sisesta kategooria ID: "))

            if category_id in valid_categories:
                return category_id, valid_categories[category_id]

            print("Sellist kategooriat ei ole nimekirjas.")

        except ValueError:
            print("Palun sisesta kategooria ID numbrina.")


def ask_question_count() -> int:
    """
    Küsib kasutajalt küsimuste arvu.

    Returns
    -------
    int
        Küsimuste arv vahemikus 1 kuni 20.
    """
    while True:
        try:
            question_count = int(
                input(f"Mitu küsimust soovid? ({MIN_QUESTION_COUNT}-{MAX_QUESTION_COUNT}): ")
            )

            if MIN_QUESTION_COUNT <= question_count <= MAX_QUESTION_COUNT:
                return question_count

            print(
                f"Küsimuste arv peab olema vahemikus "
                f"{MIN_QUESTION_COUNT} kuni {MAX_QUESTION_COUNT}."
            )

        except ValueError:
            print("Palun sisesta küsimuste arv numbrina.")


def ask_question_type() -> str:
    """
    Küsib kasutajalt küsimuste tüübi.

    Returns
    -------
    str
        Küsimuse tüüp: multiple või boolean.
    """
    while True:
        question_type = input("Sisesta küsimuste tüüp (multiple/boolean): ").strip().lower()

        if question_type in QUESTION_TYPES:
            return question_type

        print("Valida saab ainult 'multiple' või 'boolean'.")

In [245]:
categories = load_categories()
print_categories(categories)

username = ask_username()
category_id, category_name = ask_category(categories)
question_count = ask_question_count()
question_type = ask_question_type()

print()
print("Valitud testi seaded:")
print(f"Kasutaja: {username}")
print(f"Kategooria: {category_name}")
print(f"Küsimuste arv: {question_count}")
print(f"Küsimuste tüüp: {question_type}")

Saadaolevad kategooriad:

9: General Knowledge
10: Entertainment: Books
11: Entertainment: Film
12: Entertainment: Music
13: Entertainment: Musicals & Theatres
14: Entertainment: Television
15: Entertainment: Video Games
16: Entertainment: Board Games
17: Science & Nature
18: Science: Computers
19: Science: Mathematics
20: Mythology
21: Sports
22: Geography
23: History
24: Politics
25: Art
26: Celebrities
27: Animals
28: Vehicles
29: Entertainment: Comics
30: Science: Gadgets
31: Entertainment: Japanese Anime & Manga
32: Entertainment: Cartoon & Animations

Valitud testi seaded:
Kasutaja: asdas
Kategooria: Entertainment: Music
Küsimuste arv: 1
Küsimuste tüüp: boolean

## 1.7 Küsimuste laadimine ja testi käivitamine

Selles osas laen API-st küsimused vastavalt kasutaja valikutele.

Seejärel loon `TriviaGame` objekti ja käivitan testi.

Testi ajal:

- kuvatakse küsimus
- kuvatakse vastusevariandid
- kasutaja valib vastuse numbri
- programm kontrollib, kas vastus oli õige
- lõpus kuvatakse skoor ja õiged vastused

In [246]:
questions = fetch_questions(
    amount=question_count,
    category_id=category_id,
    question_type=question_type
)

game = TriviaGame(
    username=username,
    questions=questions
)

game.run()
game.print_score()
game.print_correct_answers()

Alustame testi. Mängija: asdas

Küsimus 1: Myoui Mina, member of Korean girl group TWICE, was born in South Korea, despite being Japanese.
1. False
2. True
Õige!

Teie skoor: 1/1

Õiged vastused:
1. Myoui Mina, member of Korean girl group TWICE, was born in South Korea, despite being Japanese.
   Õige vastus: False

## 1.8 Tulemuse salvestamine CSV-faili

Selles osas loon funktsiooni, mis salvestab testi tulemuse CSV-faili.

CSV-faili salvestatakse:

- kasutajanimi
- kategooria
- küsimuste arv
- küsimuste tüüp
- skoor
- kuupäev

Kui faili veel ei ole, siis programm loob selle ja lisab ka päiserea.

In [247]:
def save_result(result: TriviaResult) -> None:
    """
    Salvestab ühe testi tulemuse CSV-faili.

    Parameters
    ----------
    result : TriviaResult
        Salvestatav testi tulemus.
    """
    file_exists = RESULTS_FILE.exists()

    with RESULTS_FILE.open(mode="a", newline="", encoding="utf-8") as file:
        writer = csv.DictWriter(file, fieldnames=CSV_FIELDNAMES)

        if not file_exists:
            writer.writeheader()

        writer.writerow(result.to_csv_row())

In [248]:
result = game.create_result()
save_result(result)

print("Tulemus salvestati CSV-faili.")
print(result)

Tulemus salvestati CSV-faili.
asdas | Entertainment: Music | 1/1 | 100.0%

## 1.9 Tulemuste statistika

Selles osas loen CSV-failist kõik varasemad tulemused tagasi sisse.

Seejärel kuvan:

- TOP 5 parimat tulemust
- keskmise tulemuse protsentides

TOP 5 sorteerin protsendi järgi, mitte ainult skoori järgi, sest küsimuste arv võib olla erinev.
Näiteks `4/5` on parem tulemus kui `5/10`.

In [249]:
def read_results() -> list[dict]:
    """
    Loeb tulemused CSV-failist.

    Returns
    -------
    list[dict]
        CSV-failist loetud tulemuste nimekiri.
    """
    if not RESULTS_FILE.exists():
        return []

    with RESULTS_FILE.open(mode="r", encoding="utf-8") as file:
        reader = csv.DictReader(file)
        return list(reader)


def add_percentage_to_results(results: list[dict]) -> list[dict]:
    """
    Lisab igale tulemusele protsendi.

    Parameters
    ----------
    results : list[dict]
        CSV-failist loetud tulemused.

    Returns
    -------
    list[dict]
        Tulemused koos protsendiga.
    """
    results_with_percentage = []

    for result in results:
        try:
            question_count = int(result["küsimuste_arv"])
            score = int(result["skoor"])

            if question_count <= 0:
                continue

            result_with_percentage = result.copy()
            result_with_percentage["küsimuste_arv"] = question_count
            result_with_percentage["skoor"] = score
            result_with_percentage["protsent"] = round(
                score / question_count * 100,
                2,
            )

            results_with_percentage.append(result_with_percentage)

        except (KeyError, ValueError):
            continue

    return results_with_percentage

In [250]:
def get_top_results(results: list[dict], count: int = DEFAULT_TOP_COUNT) -> list[dict]:
    """
    Leiab parimad tulemused protsendi järgi.

    Parameters
    ----------
    results : list[dict]
        Tulemuste nimekiri.
    count : int
        Mitu tulemust tagastatakse.

    Returns
    -------
    list[dict]
        Parimad tulemused.
    """
    return sorted(
        results,
        key=lambda result: (result["protsent"], result["skoor"]),
        reverse=True
    )[:count]


def get_average_percentage(results: list[dict]) -> float:
    """
    Arvutab kõikide tulemuste keskmise protsendi.

    Parameters
    ----------
    results : list[dict]
        Tulemuste nimekiri.

    Returns
    -------
    float
        Keskmine tulemus protsendina.
    """
    if not results:
        return 0.0

    total = sum(result["protsent"] for result in results)
    return round(total / len(results), 2)


def print_top_results(results: list[dict]) -> None:
    """
    Väljastab TOP tulemused ekraanile.

    Parameters
    ----------
    results : list[dict]
        Tulemuste nimekiri.
    """
    if not results:
        print("Tulemusi pole veel salvestatud.")
        return

    print("TOP 5 tulemused:")
    print()

    for index, result in enumerate(results, start=1):
        print(
            f'{index}. {result["kasutajanimi"]} | '
            f'{result["kategooria"]} | '
            f'{result["skoor"]}/{result["küsimuste_arv"]} | '
            f'{result["protsent"]}% | '
            f'{result["kuupäev"]}'
        )

In [251]:
results = read_results()
results = add_percentage_to_results(results)

top_results = get_top_results(results)
average_percentage = get_average_percentage(results)

print_top_results(top_results)

print()
print(f"Keskmine tulemus: {average_percentage}%")

TOP 5 tulemused:

1. 3asd | Entertainment: Musicals & Theatres | 2/2 | 100.0% | 2026-05-04 21:36:10
2. c | Entertainment: Music | 1/1 | 100.0% | 2026-05-01 19:04:05
3. d | Entertainment: Musicals & Theatres | 1/1 | 100.0% | 2026-05-01 19:04:27
4. e | Geography | 1/1 | 100.0% | 2026-05-01 19:04:44
5. t | Entertainment: Music | 1/1 | 100.0% | 2026-05-01 19:05:39

Keskmine tulemus: 53.33%

# Ülesanne 2. Nutika kodu andurite jälgimissüsteem (IoT)

Selles ülesandes loon nutika kodu andurite jälgimissüsteemi.

Programm kasutab:

- CSV-faili andurite toorandmete hoidmiseks
- YAML-faili süsteemi konfiguratsiooni ja piirangute hoidmiseks
- JSON-faili häirete logi salvestamiseks
- Pandast andmete analüüsimiseks

Süsteem loeb anduriandmed, kontrollib väärtuseid YAML-is määratud piiride põhjal, salvestab häired JSON-faili ning koostab Pandase abil päringud ja aruanded.

## Konstandid

In [252]:
SENSOR_DATA_FILE = Path("sensor_data.csv")
IOT_CONFIG_FILE = Path("iot_config.yaml")
ALARMS_FILE = Path("alarms.json")

DATETIME_FORMAT = "%Y-%m-%d %H:%M:%S"

HIGH_TEMPERATURE_LIMIT = 25
LAST_DAYS_FOR_LIGHT = 7
LAST_HOURS_FOR_MOTION = 48
LAST_DAYS_FOR_HUMIDITY = 14
RECENT_ALARM_COUNT = 5

REQUIRED_SENSOR_COLUMNS = {
    "sensor_id",
    "sensor_type",
    "value",
    "unit",
    "location",
    "timestamp",
}

SENSOR_TYPE_NAMES = {
    "temperature": "Temperatuur",
    "humidity": "Niiskus",
    "light": "Valgustase",
    "motion": "Liikumine",
}

## 2.1 Failide loomine

Kõigepealt loon kolm faili:

1. `sensor_data.csv` — andurite toorandmed
2. `iot_config.yaml` — andurite konfiguratsioon ja piirangud
3. `alarms.json` — häirete logi

CSV-failis on andurite mõõtmised.  
YAML-failis on kirjas andurite nimed, asukohad, lubatud piirid ja süsteemi seaded.  
JSON-faili salvestatakse häired, kui väärtus ületab YAML-is määratud piiri.

In [253]:
sensor_rows = [
    ["TEMP_01", "temperature", 21.5, "C", "living room", "2026-03-01 10:00:00"],
    ["TEMP_02", "temperature", 31.5, "C", "kitchen", "2026-03-02 14:23:00"],
    ["TEMP_03", "temperature", 15.2, "C", "bedroom", "2026-03-03 08:15:00"],
    ["TEMP_04", "temperature", 26.4, "C", "garage", "2026-03-04 19:30:00"],

    ["HUM_01", "humidity", 42.0, "%", "living room", "2026-03-05 12:00:00"],
    ["HUM_02", "humidity", 68.5, "%", "bathroom", "2026-03-08 09:45:00"],
    ["HUM_03", "humidity", 76.2, "%", "bedroom", "2026-03-10 21:10:00"],
    ["HUM_04", "humidity", 38.4, "%", "kitchen", "2026-03-12 16:40:00"],

    ["LIGHT_01", "light", 350, "lux", "living room", "2026-03-06 11:15:00"],
    ["LIGHT_02", "light", 120, "lux", "bedroom", "2026-03-09 20:00:00"],
    ["LIGHT_03", "light", 780, "lux", "kitchen", "2026-03-11 13:30:00"],
    ["LIGHT_04", "light", 950, "lux", "garage", "2026-03-13 18:25:00"],

    ["MOT_01", "motion", 1, "1/0", "living room", "2026-03-13 22:10:00"],
    ["MOT_02", "motion", 0, "1/0", "bedroom", "2026-03-14 07:30:00"],
    ["MOT_03", "motion", 1, "1/0", "garage", "2026-03-14 23:50:00"],
    ["MOT_04", "motion", 1, "1/0", "kitchen", "2026-03-15 01:20:00"],
]

In [254]:
with SENSOR_DATA_FILE.open(mode="w", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerow([
        "sensor_id",
        "sensor_type",
        "value",
        "unit",
        "location",
        "timestamp",
    ])
    writer.writerows(sensor_rows)

print(f"CSV-fail loodud: {SENSOR_DATA_FILE}")

CSV-fail loodud: sensor_data.csv

## YAML konfiguratsioon

In [255]:
iot_config = {
    "sensors": {
        "TEMP_01": {"name": "Elutoa temperatuuriandur", "location": "living room"},
        "TEMP_02": {"name": "Köögi temperatuuriandur", "location": "kitchen"},
        "TEMP_03": {"name": "Magamistoa temperatuuriandur", "location": "bedroom"},
        "TEMP_04": {"name": "Garaaži temperatuuriandur", "location": "garage"},

        "HUM_01": {"name": "Elutoa niiskusandur", "location": "living room"},
        "HUM_02": {"name": "Vannitoa niiskusandur", "location": "bathroom"},
        "HUM_03": {"name": "Magamistoa niiskusandur", "location": "bedroom"},
        "HUM_04": {"name": "Köögi niiskusandur", "location": "kitchen"},

        "LIGHT_01": {"name": "Elutoa valgusandur", "location": "living room"},
        "LIGHT_02": {"name": "Magamistoa valgusandur", "location": "bedroom"},
        "LIGHT_03": {"name": "Köögi valgusandur", "location": "kitchen"},
        "LIGHT_04": {"name": "Garaaži valgusandur", "location": "garage"},

        "MOT_01": {"name": "Elutoa liikumisandur", "location": "living room"},
        "MOT_02": {"name": "Magamistoa liikumisandur", "location": "bedroom"},
        "MOT_03": {"name": "Garaaži liikumisandur", "location": "garage"},
        "MOT_04": {"name": "Köögi liikumisandur", "location": "kitchen"},
    },
    "limits": {
        "temperature": {"min": 16, "max": 28},
        "humidity": {"min": 30, "max": 70},
        "light": {"min": 0, "max": 900},
        "motion": {"min": 0, "max": 1}
    },
    "alarm_settings": {
        "enabled": True,
        "save_to_file": True
    },
    "system_settings": {
        "reading_interval_seconds": 60,
        "timezone": "Europe/Tallinn"
    }
}

In [256]:
with IOT_CONFIG_FILE.open(mode="w", encoding="utf-8") as file:
    yaml.dump(
        iot_config,
        file,
        allow_unicode=True,
        sort_keys=False
    )

print(f"YAML-fail loodud: {IOT_CONFIG_FILE}")

YAML-fail loodud: iot_config.yaml

In [257]:
with ALARMS_FILE.open(mode="w", encoding="utf-8") as file:
    json.dump([], file, ensure_ascii=False, indent=4)

print(f"JSON häirelogi loodud: {ALARMS_FILE}")

JSON häirelogi loodud: alarms.json

## 2.2 Failide lugemine

Nüüd loon funktsioonid, mis loevad loodud failid uuesti programmi sisse.

Loen:

- `sensor_data.csv` Pandase DataFrame'iks
- `iot_config.yaml` Pythoni sõnastikuks
- `alarms.json` Pythoni listiks

CSV-faili puhul teisendan ka `timestamp` tulba kuupäeva ja kellaaja formaati, et hiljem oleks lihtsam teha ajapõhiseid päringuid.

In [258]:
def read_sensor_data(filename: Path) -> pd.DataFrame:
    """
    Loeb andurite CSV-faili Pandase DataFrame'iks.
    """
    if not filename.exists():
        raise FileNotFoundError(f"CSV-faili ei leitud: {filename}")

    data = pd.read_csv(filename)

    missing_columns = REQUIRED_SENSOR_COLUMNS - set(data.columns)
    if missing_columns:
        raise ValueError(f"CSV-failis puuduvad veerud: {missing_columns}")

    data["timestamp"] = pd.to_datetime(
        data["timestamp"],
        format=DATETIME_FORMAT,
        errors="raise",
    )

    data["value"] = pd.to_numeric(data["value"], errors="raise")

    return data


def read_iot_config(filename: Path) -> dict:
    """
    Loeb YAML konfiguratsioonifaili.
    """
    if not filename.exists():
        raise FileNotFoundError(f"YAML-faili ei leitud: {filename}")

    with filename.open(mode="r", encoding="utf-8") as file:
        config = yaml.safe_load(file)

    if not isinstance(config, dict):
        raise ValueError("YAML konfiguratsioon peab olema sõnastik.")

    required_keys = {"sensors", "limits", "alarm_settings", "system_settings"}
    missing_keys = required_keys - set(config.keys())

    if missing_keys:
        raise ValueError(f"YAML konfiguratsioonis puuduvad võtmed: {missing_keys}")

    return config


def read_alarms(filename: Path) -> list[dict]:
    """
    Loeb JSON häirelogi.
    """
    if not filename.exists():
        return []

    try:
        with filename.open(mode="r", encoding="utf-8") as file:
            alarms = json.load(file)

    except json.JSONDecodeError:
        return []

    if not isinstance(alarms, list):
        return []

    return alarms

In [259]:
sensor_data = read_sensor_data(SENSOR_DATA_FILE)
config = read_iot_config(IOT_CONFIG_FILE)
alarms = read_alarms(ALARMS_FILE)

print("Andurite andmed:")
display(sensor_data)

print("YAML konfiguratsiooni põhivõtmed:")
print(config.keys())

print()
print("Häirete arv JSON-failis:")
print(len(alarms))

Andurite andmed:

   sensor_id  sensor_type  value unit     location           timestamp
0    TEMP_01  temperature   21.5    C  living room 2026-03-01 10:00:00
1    TEMP_02  temperature   31.5    C      kitchen 2026-03-02 14:23:00
2    TEMP_03  temperature   15.2    C      bedroom 2026-03-03 08:15:00
3    TEMP_04  temperature   26.4    C       garage 2026-03-04 19:30:00
4     HUM_01     humidity   42.0    %  living room 2026-03-05 12:00:00
5     HUM_02     humidity   68.5    %     bathroom 2026-03-08 09:45:00
6     HUM_03     humidity   76.2    %      bedroom 2026-03-10 21:10:00
7     HUM_04     humidity   38.4    %      kitchen 2026-03-12 16:40:00
8   LIGHT_01        light  350.0  lux  living room 2026-03-06 11:15:00
9   LIGHT_02        light  120.0  lux      bedroom 2026-03-09 20:00:00
10  LIGHT_03        light  780.0  lux      kitchen 2026-03-11 13:30:00
11  LIGHT_04        light  950.0  lux       garage 2026-03-13 18:25:00
12    MOT_01       motion    1.0  1/0  living room 2026-03-13 22:10:00
13    MOT_02       motion    0.0  1/0      bedroom 2026-03-14 07:30:00
14    MOT_03       motion    1.0  1/0       garage 2026-03-14 23:50:00
15    MOT_04       motion    1.0  1/0      kitchen 2026-03-15 01:20:00

YAML konfiguratsiooni põhivõtmed:
dict_keys(['sensors', 'limits', 'alarm_settings', 'system_settings'])

Häirete arv JSON-failis:
0

## 2.3 Häirete tuvastamine

Selles osas kontrollin andurite väärtuseid YAML konfiguratsioonis määratud piirangute põhjal.

Kui anduri väärtus on:

- väiksem kui lubatud miinimum
- suurem kui lubatud maksimum

siis loon häire kirje ja salvestan selle hiljem JSON-faili.

Näiteks kui temperatuuri maksimum on `28`, aga köögi temperatuuriandur näitab `31.5`, siis tekib häire.

In [260]:
def create_alarm_message(sensor_type: str, value: float, minimum: float, maximum: float) -> str:
    """
    Loob kasutajasõbraliku häiresõnumi.
    """
    sensor_name = SENSOR_TYPE_NAMES.get(sensor_type, sensor_type)

    if value < minimum:
        return f"{sensor_name} ({value}) on alla lubatud miinimumi {minimum}."

    if value > maximum:
        return f"{sensor_name} ({value}) ületab lubatud maksimumi {maximum}."

    return "Häiret ei ole."

In [261]:
def create_alarm(row: pd.Series, alarm_number: int, limits: dict) -> dict:
    """
    Loob ühe häire kirje.
    """
    sensor_type = row["sensor_type"]
    value = row["value"]
    minimum = limits[sensor_type]["min"]
    maximum = limits[sensor_type]["max"]

    return {
        "alarm_id": f"A{alarm_number:03}",
        "sensor_id": row["sensor_id"],
        "sensor_type": sensor_type,
        "value": value,
        "threshold_min": minimum,
        "threshold_max": maximum,
        "location": row["location"],
        "timestamp": row["timestamp"].strftime(DATETIME_FORMAT),
        "message": create_alarm_message(sensor_type, value, minimum, maximum),
    }

In [262]:
def get_sensor_limits(sensor_type: str, limits: dict) -> tuple[float, float] | None:
    """
    Tagastab anduritüübi lubatud miinimumi ja maksimumi.

    Kui anduritüüpi konfiguratsioonis ei ole, tagastab None.
    Kui anduritüüp on olemas, aga puudub min või max, tõstab vea.
    """
    if sensor_type not in limits:
        return None

    sensor_limits = limits[sensor_type]

    if "min" not in sensor_limits or "max" not in sensor_limits:
        raise ValueError(f"Anduritüübil '{sensor_type}' puudub min või max piir.")

    return sensor_limits["min"], sensor_limits["max"]

In [263]:
def detect_alarms(sensor_data: pd.DataFrame, config: dict) -> list[dict]:
    """
    Kontrollib andurite andmeid ja loob häired, kui väärtus ületab lubatud piirid.
    """
    if not config["alarm_settings"].get("enabled", True):
        return []

    alarms = []
    limits = config["limits"]

    for _, row in sensor_data.iterrows():
        sensor_type = row["sensor_type"]
        sensor_limits = get_sensor_limits(sensor_type, limits)

        if sensor_limits is None:
            continue

        minimum, maximum = sensor_limits
        value = row["value"]

        if value < minimum or value > maximum:
            alarm = create_alarm(row, len(alarms) + 1, limits)
            alarms.append(alarm)

    return alarms

In [264]:
def save_alarms(alarms: list[dict], filename: Path, config: dict) -> None:
    """
    Salvestab häired JSON-faili, kui konfiguratsioon seda lubab.
    """
    if not config["alarm_settings"].get("save_to_file", True):
        print("Häirete salvestamine on konfiguratsioonis välja lülitatud.")
        return

    with filename.open(mode="w", encoding="utf-8") as file:
        json.dump(alarms, file, ensure_ascii=False, indent=4)

In [265]:
alarms = detect_alarms(sensor_data, config)
save_alarms(alarms, ALARMS_FILE, config)

print(f"Tuvastatud häirete arv: {len(alarms)}")
print(f"Häired salvestati faili: {ALARMS_FILE}")

for alarm in alarms:
    print(
        f'{alarm["alarm_id"]}: '
        f'{alarm["sensor_id"]} | '
        f'{alarm["sensor_type"]} | '
        f'{alarm["value"]} | '
        f'{alarm["location"]} | '
        f'{alarm["message"]}'
    )

Tuvastatud häirete arv: 4
Häired salvestati faili: alarms.json
A001: TEMP_02 | temperature | 31.5 | kitchen | Temperatuur (31.5) ületab lubatud maksimumi 28.
A002: TEMP_03 | temperature | 15.2 | bedroom | Temperatuur (15.2) on alla lubatud miinimumi 16.
A003: HUM_03 | humidity | 76.2 | bedroom | Niiskus (76.2) ületab lubatud maksimumi 70.
A004: LIGHT_04 | light | 950.0 | garage | Valgustase (950.0) ületab lubatud maksimumi 900.

## 2.4 Päringud Pandase abil

Selles osas kasutan `sensor_data` DataFrame'i ja teen ülesandes nõutud päringud.

Vaja leida:

1. kõik temperatuurinäidud, mis on suuremad kui 25°C
2. iga ruumi viimane liikumise tuvastamise aeg
3. viimase 7 päeva suurim ja väikseim valgustase
4. ruumid, kus on toimunud liikumist viimase 48 tunni jooksul
5. ruum, kus on viimase 14 päeva jooksul registreeritud kõrgeim niiskustase

In [266]:
def find_high_temperatures(sensor_data: pd.DataFrame) -> pd.DataFrame:
    """
    Leiab kõik temperatuurinäidud, mis on suuremad kui 25°C.

    Parameters
    ----------
    sensor_data : pd.DataFrame
        Andurite andmed.

    Returns
    -------
    pd.DataFrame
        Temperatuurinäidud üle 25°C.
    """
    return sensor_data[
        (sensor_data["sensor_type"] == "temperature") &
        (sensor_data["value"] > HIGH_TEMPERATURE_LIMIT)
    ]


high_temperatures = find_high_temperatures(sensor_data)

print("Temperatuurinäidud üle 25°C:")
display(high_temperatures)

Temperatuurinäidud üle 25°C:

  sensor_id  sensor_type  value unit location           timestamp
1   TEMP_02  temperature   31.5    C  kitchen 2026-03-02 14:23:00
3   TEMP_04  temperature   26.4    C   garage 2026-03-04 19:30:00

In [267]:
def find_last_motion_by_room(sensor_data: pd.DataFrame) -> pd.DataFrame:
    """
    Leiab iga ruumi viimase liikumise tuvastamise aja.

    Parameters
    ----------
    sensor_data : pd.DataFrame
        Andurite andmed.

    Returns
    -------
    pd.DataFrame
        Iga ruumi viimane liikumise aeg.
    """
    motion_data = sensor_data[
        (sensor_data["sensor_type"] == "motion") &
        (sensor_data["value"] == 1)
    ]

    return (
        motion_data
        .groupby("location")["timestamp"]
        .max()
        .reset_index()
        .rename(columns={"timestamp": "last_motion_time"})
    )


last_motion_by_room = find_last_motion_by_room(sensor_data)

print("Iga ruumi viimane liikumise tuvastamise aeg:")
display(last_motion_by_room)

Iga ruumi viimane liikumise tuvastamise aeg:

      location    last_motion_time
0       garage 2026-03-14 23:50:00
1      kitchen 2026-03-15 01:20:00
2  living room 2026-03-13 22:10:00

In [268]:
def find_light_min_max_last_7_days(sensor_data: pd.DataFrame) -> pd.DataFrame:
    """
    Leiab viimase 7 päeva suurima ja väikseima valgustaseme.

    Parameters
    ----------
    sensor_data : pd.DataFrame
        Andurite andmed.

    Returns
    -------
    pd.DataFrame
        Minimaalne ja maksimaalne valgustase.
    """
    latest_time = sensor_data["timestamp"].max()
    start_time = latest_time - timedelta(days=LAST_DAYS_FOR_LIGHT)

    light_data = sensor_data[
        (sensor_data["sensor_type"] == "light") &
        (sensor_data["timestamp"] >= start_time)
    ]

    if light_data.empty:
        return pd.DataFrame(columns=["measure", "value"])

    return (
        light_data["value"]
        .agg(["min", "max"])
        .reset_index()
        .rename(columns={"index": "measure"})
    )

light_min_max = find_light_min_max_last_7_days(sensor_data)

print("Viimase 7 päeva väikseim ja suurim valgustase:")
display(light_min_max)

Viimase 7 päeva väikseim ja suurim valgustase:

  measure  value
0     min  120.0
1     max  950.0

In [269]:
def find_rooms_with_motion_last_48_hours(sensor_data: pd.DataFrame) -> list[str]:
    """
    Leiab ruumid, kus on toimunud liikumist viimase 48 tunni jooksul.

    Parameters
    ----------
    sensor_data : pd.DataFrame
        Andurite andmed.

    Returns
    -------
    list[str]
        Ruumide nimekiri.
    """
    latest_time = sensor_data["timestamp"].max()
    start_time = latest_time - timedelta(hours=LAST_HOURS_FOR_MOTION)

    motion_data = sensor_data[
        (sensor_data["sensor_type"] == "motion") &
        (sensor_data["value"] == 1) &
        (sensor_data["timestamp"] >= start_time)
    ]

    return sorted(motion_data["location"].unique())


rooms_with_motion = find_rooms_with_motion_last_48_hours(sensor_data)

print("Ruumid, kus on viimase 48 tunni jooksul toimunud liikumist:")
for room in rooms_with_motion:
    print(room)

Ruumid, kus on viimase 48 tunni jooksul toimunud liikumist:
garage
kitchen
living room

In [270]:
def find_room_with_highest_humidity_last_14_days(sensor_data: pd.DataFrame) -> pd.DataFrame:
    """
    Leiab ruumi, kus on viimase 14 päeva jooksul registreeritud kõrgeim niiskustase.

    Parameters
    ----------
    sensor_data : pd.DataFrame
        Andurite andmed.

    Returns
    -------
    pd.DataFrame
        Kõrgeima niiskustasemega mõõtmine.
    """
    latest_time = sensor_data["timestamp"].max()
    start_time = latest_time - timedelta(days=LAST_DAYS_FOR_HUMIDITY)

    humidity_data = sensor_data[
        (sensor_data["sensor_type"] == "humidity") &
        (sensor_data["timestamp"] >= start_time)
    ]

    if humidity_data.empty:
        return pd.DataFrame(columns=sensor_data.columns)

    max_index = humidity_data["value"].idxmax()
    return humidity_data.loc[[max_index]]


highest_humidity = find_room_with_highest_humidity_last_14_days(sensor_data)

print("Ruum, kus on viimase 14 päeva jooksul kõrgeim niiskustase:")
display(highest_humidity)

Ruum, kus on viimase 14 päeva jooksul kõrgeim niiskustase:

  sensor_id sensor_type  value unit location           timestamp
6    HUM_03    humidity   76.2    %  bedroom 2026-03-10 21:10:00

## 2.5 Andmete väljastamine failidest

Selles osas loen andmed YAML ja JSON failidest ning kuvan need kasutajale loetaval kujul.

YAML konfiguratsioonist kuvan:

- kõik andurid ja nende asukohad
- igale anduritüübile määratud piirangud
- süsteemi seaded

JSON häirelogist kuvan:

- kõik häired
- häirete arvu anduri tüübi kaupa
- häirete arvu ruumi kaupa
- viimased 5 häiret

In [271]:
def print_sensor_list(config: dict) -> None:
    """
    Kuvab YAML konfiguratsioonist kõik andurid ja nende asukohad.

    Parameters
    ----------
    config : dict
        YAML konfiguratsioon.
    """
    print("Kõigi andurite nimekiri ja asukohad:")
    print()

    sensors = config["sensors"]

    for sensor_id, sensor_info in sensors.items():
        print(
            f'{sensor_id}: '
            f'{sensor_info["name"]} | '
            f'Asukoht: {sensor_info["location"]}'
        )


def print_sensor_limits(config: dict) -> None:
    """
    Kuvab YAML konfiguratsioonist anduritüüpide piirangud.

    Parameters
    ----------
    config : dict
        YAML konfiguratsioon.
    """
    print("Iga anduri tüübi piirangud:")
    print()

    limits = config["limits"]

    for sensor_type, limit_values in limits.items():
        print(
            f'{sensor_type}: '
            f'min = {limit_values["min"]}, '
            f'max = {limit_values["max"]}'
        )


def print_system_settings(config: dict) -> None:
    """
    Kuvab YAML konfiguratsioonist süsteemi seaded.

    Parameters
    ----------
    config : dict
        YAML konfiguratsioon.
    """
    print("Süsteemi seaded:")
    print()

    system_settings = config["system_settings"]
    alarm_settings = config["alarm_settings"]

    print("Üldised seaded:")
    for key, value in system_settings.items():
        print(f"{key}: {value}")

    print()
    print("Häirete seaded:")
    for key, value in alarm_settings.items():
        print(f"{key}: {value}")

In [272]:
config = read_iot_config(IOT_CONFIG_FILE)

print_sensor_list(config)

print()
print("-" * 50)
print()

print_sensor_limits(config)

print()
print("-" * 50)
print()

print_system_settings(config)

Kõigi andurite nimekiri ja asukohad:

TEMP_01: Elutoa temperatuuriandur | Asukoht: living room
TEMP_02: Köögi temperatuuriandur | Asukoht: kitchen
TEMP_03: Magamistoa temperatuuriandur | Asukoht: bedroom
TEMP_04: Garaaži temperatuuriandur | Asukoht: garage
HUM_01: Elutoa niiskusandur | Asukoht: living room
HUM_02: Vannitoa niiskusandur | Asukoht: bathroom
HUM_03: Magamistoa niiskusandur | Asukoht: bedroom
HUM_04: Köögi niiskusandur | Asukoht: kitchen
LIGHT_01: Elutoa valgusandur | Asukoht: living room
LIGHT_02: Magamistoa valgusandur | Asukoht: bedroom
LIGHT_03: Köögi valgusandur | Asukoht: kitchen
LIGHT_04: Garaaži valgusandur | Asukoht: garage
MOT_01: Elutoa liikumisandur | Asukoht: living room
MOT_02: Magamistoa liikumisandur | Asukoht: bedroom
MOT_03: Garaaži liikumisandur | Asukoht: garage
MOT_04: Köögi liikumisandur | Asukoht: kitchen

--------------------------------------------------

Iga anduri tüübi piirangud:

temperature: min = 16, max = 28
humidity: min = 30, max = 70
light: min = 0, max = 900
motion: min = 0, max = 1

--------------------------------------------------

Süsteemi seaded:

Üldised seaded:
reading_interval_seconds: 60
timezone: Europe/Tallinn

Häirete seaded:
enabled: True
save_to_file: True

In [273]:
def print_all_alarms(alarms: list[dict]) -> None:
    """
    Kuvab kõik JSON-failis olevad häired.

    Parameters
    ----------
    alarms : list[dict]
        Häirete nimekiri.
    """
    print("Kõik häired:")
    print()

    if not alarms:
        print("Häireid ei ole.")
        return

    for alarm in alarms:
        print(
            f'{alarm["alarm_id"]}: '
            f'{alarm["sensor_id"]} | '
            f'{alarm["sensor_type"]} | '
            f'{alarm["value"]} | '
            f'{alarm["location"]} | '
            f'{alarm["timestamp"]} | '
            f'{alarm["message"]}'
        )


def count_alarms_by_key(alarms: list[dict], key: str) -> dict[str, int]:
    """
    Loendab häired etteantud võtme järgi.
    """
    result = {}

    for alarm in alarms:
        if key not in alarm:
            continue

        value = alarm[key]
        result[value] = result.get(value, 0) + 1

    return result


def get_recent_alarms(alarms: list[dict], count: int = RECENT_ALARM_COUNT) -> list[dict]:
    """
    Tagastab viimased häired kuupäeva järgi.

    Parameters
    ----------
    alarms : list[dict]
        Häirete nimekiri.
    count : int
        Mitu viimast häiret tagastatakse.

    Returns
    -------
    list[dict]
        Viimased häired.
    """
    sorted_alarms = sorted(
        alarms,
        key=lambda alarm: alarm["timestamp"],
        reverse=True
    )

    return sorted_alarms[:count]

In [274]:
alarms = read_alarms(ALARMS_FILE)

print_all_alarms(alarms)

print()
print("-" * 50)
print()

print("Häired anduri tüübi kaupa:")
alarms_by_type = count_alarms_by_key(alarms, "sensor_type")

for sensor_type, count in alarms_by_type.items():
    print(f"{sensor_type}: {count}")

print()
print("-" * 50)
print()

print("Häired ruumi kaupa:")
alarms_by_location = count_alarms_by_key(alarms, "location")

for location, count in alarms_by_location.items():
    print(f"{location}: {count}")

print()
print("-" * 50)
print()

print("Viimased 5 häiret:")
recent_alarms = get_recent_alarms(alarms)

for alarm in recent_alarms:
    print(
        f'{alarm["alarm_id"]}: '
        f'{alarm["sensor_id"]} | '
        f'{alarm["location"]} | '
        f'{alarm["timestamp"]} | '
        f'{alarm["message"]}'
    )

Kõik häired:

A001: TEMP_02 | temperature | 31.5 | kitchen | 2026-03-02 14:23:00 | Temperatuur (31.5) ületab lubatud maksimumi 28.
A002: TEMP_03 | temperature | 15.2 | bedroom | 2026-03-03 08:15:00 | Temperatuur (15.2) on alla lubatud miinimumi 16.
A003: HUM_03 | humidity | 76.2 | bedroom | 2026-03-10 21:10:00 | Niiskus (76.2) ületab lubatud maksimumi 70.
A004: LIGHT_04 | light | 950.0 | garage | 2026-03-13 18:25:00 | Valgustase (950.0) ületab lubatud maksimumi 900.

--------------------------------------------------

Häired anduri tüübi kaupa:
temperature: 2
humidity: 1
light: 1

--------------------------------------------------

Häired ruumi kaupa:
kitchen: 1
bedroom: 2
garage: 1

--------------------------------------------------

Viimased 5 häiret:
A004: LIGHT_04 | garage | 2026-03-13 18:25:00 | Valgustase (950.0) ületab lubatud maksimumi 900.
A003: HUM_03 | bedroom | 2026-03-10 21:10:00 | Niiskus (76.2) ületab lubatud maksimumi 70.
A002: TEMP_03 | bedroom | 2026-03-03 08:15:00 | Temperatuur (15.2) on alla lubatud miinimumi 16.
A001: TEMP_02 | kitchen | 2026-03-02 14:23:00 | Temperatuur (31.5) ületab lubatud maksimumi 28.

# AI kasutamise vorm

**Üldinfo:**

Nimi: Fred Brosman

Ülesanne: CSV, JSON, YAML

Kuupäev: 05.05.2026

---

**1. Milliseid AI tööriistu kasutasid?**

ChatGPT, Copilot

---

**2. Too välja 2-3 näidet AI-prompt'idest, mida kasutasid:**

a) "Role: Tegutse Python programmeerimise juhendajana.  
Task: Aita mul luua Trivia API põhine test, kus kasutaja saab valida kategooria, küsimuste arvu ja küsimuse tüübi.  
Format: Jaga lahendus väikesteks Jupyter Notebooki osadeks koos markdown selgitustega.  
Goal: Soovin teha arusaadava API-põhise testi programmi."

b) "Role: Tegutse Python andmetöötluse juhendajana.  
Task: Aita mul luua IoT andurite jälgimissüsteem, mis kasutab CSV-, YAML- ja JSON-faile ning Pandast.  
Format: Näita lahendust samm-sammult koos funktsioonide ja selgitustega.  
Goal: Soovin aru saada, kuidas erinevaid failivorminguid koos kasutada."

c) "Role: Tegutse koodi ülevaatajana.  
Task: Vaata üle minu lahendus ja too välja võimalikud servajuhud, clean code probleemid ja parandused.  
Format: Anna lühike tagasiside ja vajadusel parandatud koodiplokid.  
Goal: Soovin enne esitamist lahenduse korrektsemaks teha."

---

**3. Millised koodiosad kirjutasid täielikult ise?**

- notebooki üldise struktuuri ja markdown-pealkirjad
- testandmete ja andurite näidisandmete kohandamise
- kasutaja sisendi testimise
- väljundite eestikeelsed tekstid
- CSV, YAML ja JSON failide loomise kontrollimise
- tulemuste kuvamise ja notebooki järjestuse kohandamise

---

**4. Milliseid AI poolt genereeritud lahendusi pidid parandama või ümber kirjutama?**

- täiendasin API päringuid veakäsitlusega
- parandasin CSV tulemuste lugemist nii, et vigased read ei katkestaks programmi
- lisasin IoT CSV-faili veergude kontrolli
- täiendasin YAML konfiguratsiooni kontrolli
- muutsin häiresõnumid kasutajasõbralikumaks ja eestikeelsemaks
- ühtlustasin failide lugemise ja kirjutamise loogikat

---

**5. Milliste probleemide lahendamisel aitas AI kõige rohkem?**

- Trivia API JSON-vastuse töötlemisel
- klasside `TriviaQuestion`, `TriviaResult` ja `TriviaGame` jaotamisel
- CSV-faili salvestamise ja statistika arvutamise loogikas
- YAML konfiguratsiooni ja JSON häirelogi kasutamisel
- Pandase päringute koostamisel
- clean code paranduste leidmisel

---

**6. Mida õppisid selle ülesande käigus tehniliselt?**

- kuidas teha API päringuid `requests` teegiga
- kuidas töödelda JSON-vastust Pythonis
- kuidas kirjutada ja lugeda CSV-faile
- kuidas kasutada YAML-faili konfiguratsiooni hoidmiseks
- kuidas salvestada häireid JSON-faili
- kuidas kasutada Pandast andmete filtreerimiseks ja grupeerimiseks
- kuidas kontrollida kasutaja sisendit ja failide sisu

---

**7. Enesehinnang:**

- [ ] **Vibe Coding** – kasutasin AI-d kiireks koodi genereerimiseks, ei muutnud palju
- [x] **Mixed** – kasutasin AI-d, aga kohandasin ja parandasin koodi
- [ ] **Deep Coding** – kasutasin AI-d abivahendina, mõistan täpselt, kuidas kood töötab

---

**8. Lühike põhjendus oma enesehinnangule:**

Kasutasin AI-d peamiselt programmi struktuuri, API päringute, failide töötlemise ja Pandase päringute koostamisel. Samas kohandasin lahendust oma notebooki stiiliga, testisin koodi, parandasin veateateid ja lisasin mitmeid kontrollimisi. Saan üldiselt aru, kuidas lahendus töötab, aga AI aitas keerulisemad osad kiiremini ja selgemalt kokku panna.